interface AppConfig {
    LISTENING_PORT: number;
    MONGODB_URI: string;
    MONGODB_RECONNECT_ATTEMPTS: number;
    MONGODB_RECONNECT_INTERVAL: number;
    SCRAPPER_URI: string;
    ENV_MODE: string;
    SERVICE_NAME: string;
    MOVIES_PER_PAGE: number;
}

const {
    LISTENING_PORT,
    MONGODB_URI,
    MONGODB_RECONNECT_ATTEMPTS,
    MONGODB_RECONNECT_INTERVAL,
    SCRAPPER_URI,
    ENV_MODE,
    npm_package_name,
} = process.env;

const DEFAULT_LISTENING_PORT = 4000;
const DEFAULT_MONGODB_URI = 'mongodb://movies-mongo:27017/movies';
const DEFAULT_MONGODB_RECONNECT_ATTEMPTS = 3;
const DEFAULT_MONGODB_RECONNECT_INTERVAL = 10;
const DEFAULT_SCRAPPER_URI = 'http://scrapper-svc:4010';

const CONFIG: AppConfig = {
    LISTENING_PORT: Number(LISTENING_PORT) || DEFAULT_LISTENING_PORT,
    MONGODB_URI: MONGODB_URI || DEFAULT_MONGODB_URI,
    MONGODB_RECONNECT_ATTEMPTS: Number(MONGODB_RECONNECT_ATTEMPTS) || DEFAULT_MONGODB_RECONNECT_ATTEMPTS,
    MONGODB_RECONNECT_INTERVAL: Number(MONGODB_RECONNECT_INTERVAL) || DEFAULT_MONGODB_RECONNECT_INTERVAL,
    SCRAPPER_URI: SCRAPPER_URI || DEFAULT_SCRAPPER_URI,
    ENV_MODE: ENV_MODE || 'DEV',
    SERVICE_NAME: npm_package_name || 'movies-api',
    MOVIES_PER_PAGE: 250,
};

export default CONFIG;
