export enum AppConfig {
    LISTENING_PORT = 'LISTENING_PORT',
    MONGODB_URI = 'MONGODB_URI',
    MONGODB_RECONNECT_ATTEMPTS = 'MONGODB_RECONNECT_ATTEMPTS',
    MONGODB_RECONNECT_INTERVAL = 'MONGODB_RECONNECT_INTERVAL',
    MOVIES_API_URI = 'MOVIES_API_URI',
    ENV_MODE = 'ENV_MODE',
    SERVICE_NAME = 'SERVICE_NAME',
    MOVIES_PER_PAGE = 'MOVIES_PER_PAGE',
    TVMAZE_URI ='TVMAZE_URI',
    TVMAZE_SHOWS_QUERY = 'TVMAZE_SHOWS_QUERY',
    TVMAZE_CAST_PATH = 'TVMAZE_CAST_PATH',
    RETRY_REQUEST_TIMEOUT = 'RETRY_REQUEST_TIMEOUT',
}
