version: '3.4'
services:
  scrapper-svc:
    build:
      context: ./services/scrapper-svc
      target: builder
    volumes:
      - type: bind
        source: ./services/scrapper-svc/build
        target: /app/build
      - type: bind
        source: ./services/scrapper-svc/src/config
        target: /app/build/config
    ports:
      - "4010:4010"
    command: yarn run start-dev

  movies-mongo:
    volumes:
      - movies-mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  movies-mongodata:
