version: '3.4'
services:
  scrapper-svc:
    image: ./some-prod-image
    restart: always

  movies-mongo:
    restart: always
    volumes:
      - ./mongo/movies/data/db:/data/db
    expose:
      - "27017"
