version: '3.4'
services:
  movies-api:
    image: ./some-prod-image
    env_file: ./services/movies-api/config.prod.env
    restart: always
    expose:
      - "4000"

  movies-mongo:
    restart: always
    volumes:
      - ./mongo/movies/data/db:/data/db
    expose:
      - "27017"
