version: '3.4'
services:
  movies-api:
    image: ./some-qa-image
    restart: always
    expose:
      - "4000"
    logging:
      driver: gelf
      options:
        gelf-address: udp://0.0.0.0:12201
        tag: movies-api

  auth-mongo:
    restart: always
    volumes:
      - ./mongo/movies/data/db:/data/db
    ports:
      - "27017:27017"
