import { MovieFromApi, Movie } from '../types/types';
import { castMock } from './cast.mock';

export const moviesMock: Movie[] = [
    {
        id: 1,
        name: 'Under the Dome',
        cast: [...castMock],
    },
    {
        id: 2,
        name: 'Person of Interest',
        cast: [
            { id: 92, name: 'Sarah Shahi', birthday: '1980-01-10' },
            { id: 91, name: 'Amy Acker', birthday: '1976-12-05' },
            { id: 91, name: 'Amy Acker', birthday: '1976-12-05' },
            { id: 89, name: 'Taraji P. Henson', birthday: '1970-09-11' },
            { id: 88, name: 'James Caviezel', birthday: '1968-09-26' },
            { id: 90, name: 'Kevin Chapman', birthday: '1962-07-29' },
            { id: 93, name: 'Michael Emerson', birthday: '1954-09-07' },
        ],
    },
    {
        id: 3,
        name: 'Bitten',
        cast: [
            { id: 176, name: 'Steve Lund', birthday: '1989-01-09' },
            { id: 173, name: 'Greyston Holt', birthday: '1985-09-30' },
            { id: 172, name: 'Laura Vandervoort', birthday: '1984-09-22' },
            { id: 175, name: 'Paul Greene', birthday: '1974-06-02' },
            { id: 174, name: 'Greg Bryk', birthday: '1972-01-01' },
            { id: 192, name: 'Michael Xavier', birthday: '' },
        ],
    },
    {
        id: 4,
        name: 'Arrow',
        cast: [
            { id: 276, name: 'Emily Bett Rickards', birthday: '1991-07-24' },
            { id: 275, name: 'Willa Holland', birthday: '1991-06-18' },
            { id: 277, name: 'Colton Haynes', birthday: '1988-07-13' },
            { id: 272, name: 'Katie Cassidy', birthday: '1986-11-25' },
            { id: 272, name: 'Katie Cassidy', birthday: '1986-11-25' },
            { id: 918, name: 'Josh Segarra', birthday: '1986-06-03' },
            { id: 34387, name: 'Juliana Harkavy', birthday: '1985-01-01' },
            { id: 273, name: 'Colin Donnell', birthday: '1982-10-09' },
            { id: 271, name: 'Stephen Amell', birthday: '1981-05-08' },
            { id: 10897, name: 'Rick Gonzalez', birthday: '1979-06-30' },
            { id: 274, name: 'David Ramsey', birthday: '1971-11-17' },
            { id: 278, name: 'Manu Bennett', birthday: '1969-10-10' },
            { id: 280, name: 'Paul Blackthorne', birthday: '1969-03-05' },
            { id: 281, name: 'John Barrowman', birthday: '1967-03-11' },
            { id: 279, name: 'Susanna Thompson', birthday: '1958-01-27' },
            { id: 45912, name: 'Echo Kellum', birthday: '' },
        ],
    },
];

export const moviesFromApiMock: MovieFromApi[] = [
    {
        id: 250,
        url: 'http://www.tvmaze.com/shows/250/kirby-buckets',
        name: 'Kirby Buckets',
        type: 'Scripted',
        language: 'English',
        genres: ['Comedy'],
        status: 'Running',
        runtime: 30,
        premiered: '2014-10-20',
        officialSite: 'http://disneyxd.disney.com/kirby-buckets',
        schedule: { time: '07:00', days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'] },
        rating: { average: null },
        weight: 69,
        network: {
            id: 25,
            name: 'Disney XD',
            country: { name: 'United States', code: 'US', timezone: 'America/New_York' },
        },
        webChannel: {
            id: 123,
            name: 'WATCH Disney XD',
            country: { name: 'United States', code: 'US', timezone: 'America/New_York' },
        },
        externals: { tvrage: 37394, thetvdb: 278449, imdb: 'tt3544772' },
        image: {
            medium: 'http://static.tvmaze.com/uploads/images/medium_portrait/1/4600.jpg',
            original: 'http://static.tvmaze.com/uploads/images/original_untouched/1/4600.jpg',
        },
        summary: `summary`,
        updated: 1514839159,
        _links: {
            self: { href: 'http://api.tvmaze.com/shows/250' },
            previousepisode: { href: 'http://api.tvmaze.com/episodes/1051658' },
        },
    },
    {
        id: 251,
        url: 'http://www.tvmaze.com/shows/251/downton-abbey',
        name: 'Downton Abbey',
        type: 'Scripted',
        language: 'English',
        genres: ['Drama', 'Family', 'Romance'],
        status: 'Ended',
        runtime: 60,
        premiered: '2010-09-26',
        officialSite: 'http://www.itv.com/downtonabbey',
        schedule: { time: '21:00', days: ['Sunday'] },
        rating: { average: 9 },
        weight: 88,
        network: { id: 35, name: 'ITV', country: { name: 'United Kingdom', code: 'GB', timezone: 'Europe/London' } },
        webChannel: null,
        externals: { tvrage: 26615, thetvdb: 193131, imdb: 'tt1606375' },
        image: {
            medium: 'http://static.tvmaze.com/uploads/images/medium_portrait/1/4601.jpg',
            original: 'http://static.tvmaze.com/uploads/images/original_untouched/1/4601.jpg',
        },
        summary: `summary`,
        updated: 1534000284,
        _links: {
            self: { href: 'http://api.tvmaze.com/shows/251' },
            previousepisode: { href: 'http://api.tvmaze.com/episodes/215207' },
        },
    },
    {
        id: 252,
        url: 'http://www.tvmaze.com/shows/252/girl-meets-world',
        name: 'Girl Meets World',
        type: 'Scripted',
        language: 'English',
        genres: ['Drama', 'Comedy', 'Family'],
        status: 'Ended',
        runtime: 30,
        premiered: '2014-06-27',
        officialSite: 'http://disneychannel.disney.com/girl-meets-world',
        schedule: { time: '18:00', days: ['Friday'] },
        rating: { average: 8.3 },
        weight: 79,
        network: {
            id: 78,
            name: 'Disney Channel',
            country: { name: 'United States', code: 'US', timezone: 'America/New_York' },
        },
        webChannel: {
            id: 83,
            name: 'Watch Disney Channel',
            country: { name: 'United States', code: 'US', timezone: 'America/New_York' },
        },
        externals: { tvrage: 33436, thetvdb: 267777, imdb: 'tt2543796' },
        image: {
            medium: 'http://static.tvmaze.com/uploads/images/medium_portrait/50/126868.jpg',
            original: 'http://static.tvmaze.com/uploads/images/original_untouched/50/126868.jpg',
        },
        summary: `summary`,
        updated: 1536662976,
        _links: {
            self: { href: 'http://api.tvmaze.com/shows/252' },
            previousepisode: { href: 'http://api.tvmaze.com/episodes/1011244' },
        },
    },
    {
        id: 253,
        url: 'http://www.tvmaze.com/shows/253/hells-kitchen',
        name: "Hell's Kitchen",
        type: 'Reality',
        language: 'English',
        genres: ['Food'],
        status: 'Running',
        runtime: 60,
        premiered: '2005-05-30',
        officialSite: 'http://www.fox.com/hells-kitchen',
        schedule: { time: '20:00', days: ['Friday'] },
        rating: { average: 7.9 },
        weight: 89,
        network: { id: 4, name: 'FOX', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } },
        webChannel: null,
        externals: { tvrage: 3828, thetvdb: 74897, imdb: 'tt0437005' },
        image: {
            medium: 'http://static.tvmaze.com/uploads/images/medium_portrait/1/4632.jpg',
            original: 'http://static.tvmaze.com/uploads/images/original_untouched/1/4632.jpg',
        },
        summary: `summary`,
        updated: 1536482008,
        _links: {
            self: { href: 'http://api.tvmaze.com/shows/253' },
            previousepisode: { href: 'http://api.tvmaze.com/episodes/1407163' },
            nextepisode: { href: 'http://api.tvmaze.com/episodes/1486757' },
        },
    },
    {
        id: 254,
        url: 'http://www.tvmaze.com/shows/254/world-series-of-poker',
        name: 'World Series of Poker',
        type: 'Sports',
        language: 'English',
        genres: [],
        status: 'Running',
        runtime: 60,
        premiered: '2006-08-22',
        officialSite: null,
        schedule: { time: '21:00', days: ['Monday', 'Tuesday', 'Sunday'] },
        rating: { average: 9 },
        weight: 89,
        network: {
            id: 180,
            name: 'ESPN2',
            country: { name: 'United States', code: 'US', timezone: 'America/New_York' },
        },
        webChannel: null,
        externals: { tvrage: 16764, thetvdb: 79028, imdb: 'tt2733512' },
        image: {
            medium: 'http://static.tvmaze.com/uploads/images/medium_portrait/1/4656.jpg',
            original: 'http://static.tvmaze.com/uploads/images/original_untouched/1/4656.jpg',
        },
        summary:
            "<p>The <b>World Series of Poker</b> is where the world's best poker players battle for the title.</p>",
        updated: 1532569057,
        _links: {
            self: { href: 'http://api.tvmaze.com/shows/254' },
            previousepisode: { href: 'http://api.tvmaze.com/episodes/1493610' },
        },
    },
];
