version: '3.4'
services:
  gateway:
    image: nginx:1.13.12-alpine
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
