export enum AppConfig {
    LISTENING_PORT = 'LISTENING_PORT',
    MONGODB_URI = 'MONGODB_URI',
    MONGODB_RECONNECT_ATTEMPTS = 'MONGODB_RECONNECT_ATTEMPTS',
    MONGODB_RECONNECT_INTERVAL = 'MONGODB_RECONNECT_INTERVAL',
    SCRAPPER_URI = 'SCRAPPER_URI',
    ENV_MODE = 'ENV_MODE',
    SERVICE_NAME = 'SERVICE_NAME',
    MOVIES_PER_PAGE = 'MOVIES_PER_PAGE',
}
